[project]
name = "teleco-daisy"
version = "0.1.4"
description = ""
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pydantic>=2",
    "requests>=2.32.2",
]

[dependency-groups]
dev = [
    "icecream>=2.1.5",
    "ruff>=0.12.3",
]
